export loadInfo from './loadInfo'
export loadAuth from './loadAuth'
export login from './login'
export logout from './logout'
export loginVk from './loginVk'
export loadStatic from './loadStatic'
export uploadStatic from './uploadStatic'
export * as widget from './widget/index'
export * as module from './module/index'
export * as lectures from './lectures/index'
export * as activeLectures from './activeLectures/index'
export * as users from './users/index'
export * as questions from './questions/index'
export * as questionBlock from './questionBlock/index'
export * as activeQuestionBlock from './activeQuestionBlock/index'
export * as visualModule from './visualModule/index'
export * as sync_v1 from './sync_v1/index' // eslint-disable-line
