// export const tabNames = ['Math', 'Greek', 'Symbols', 'Typeface', 'Functions',
//                      '{ || }', '+ / -', '-->', '< > =', 'AMS', 'AMS < > =',
//                      'AMS NOT < > =']

export const tabNames = ['Math', 'Greek', 'Symbols', 'Typeface',
                    '{ || }', '+ / -', '-->']


export const tabContent = {
  'Math': [[['\\sum', '\\bigsqcup'], ['\\prod', '\\bigvee'], ['\\coprod',
          '\\bigwedge'], ['\\int', '\\bigodot'], ['\\oint', '\\bigotimes'],
          ['\\bigcap', '\\bigoplus'], ['\\bigcup', '\\biguplus']],
          [['\\mathscr{A}', '\\mathcal{C}'],
          ['\\mathbb{R}', '\\mathrm{T}'],
          ['\\mathbf{B}', '\\mathfrak{F}']],
          [['x^k', 'x_k']], [['\\hat{a}', '\\tilde{a}'],
          ['\\check{a}', '\\bar{a}'], ['\\breve{a}', '\\vec{a}'], ['\\acute{a}',
          '\\dot{a}'], ['\\grave{a}', '\\ddot{a}']], [['\\sqrt{abc}',
          '\\sqrt[n]{abc}']], [['\\overline{abc}', '\\underline{abc}']],
          [['\\binom{m}{k}', '\\frac{num}{den}']]],
  'Greek': [[['\\Gamma', '\\Sigma'], ['\\Delta', '\\Upsilon'], ['\\Theta', '\\Phi'],
          ['\\Lambda', '\\Psi'], ['\\Xi', '\\Omega'], ['\\Pi', '']], [['\\alpha',
          '\\xi'], ['\\beta', '\\omicron'], ['\\gamma', '\\pi'], ['\\delta',
          '\\varpi'], ['\\epsilon', '\\rho'], ['\\varepsilon', '\\varrho'],
          ['\\zeta', '\\sigma'], ['\\eta', '\\varsigma'], ['\\theta', '\\tau'],
          ['\\vartheta', '\\upsilon'], ['\\iota', '\\phi'], ['\\kappa', '\\varphi'],
          ['\\lambda', '\\chi'], ['\\mu', '\\psi'], ['\\nu', '\\omega']],
          [['\\digamma', '\\gimel'], ['\\beth', '\\daleth']]],
  'Symbols': [[['\\aleph', '\\infty'], ['\\hbar', '\\partial'], ['\\imath',
          '\\nabla'], ['\\jmath', '\\triangle'], ['\\ell', '\\forall'], ['\\wp',
          '\\exists'], ['\\Re', '\\neg'], ['\\Im', '\\surd'], ['\\prime', '\\top'],
          ['\\emptyset', '\\bot'], ['\\angle', '\\backslash'], ['\\mho', '\\Box'],
          ['\\cdot', '\\diamond']], [['\\dag', '\\ddag']], [['\\ulcorner',
          '\\llcorner'], ['\\urcorner', '\\lrcorner']], [['\\ldots', '\\vdots'],
          ['\\cdots', '\\ddots']]],
  'Typeface': [[['\\mathbf{Bold}'], ['\\mathit{Italic}'], ['\\mathrm{Roman}'],
          ['\\mathsf{Sans}'], ['\\mathtt{TT}']]],
  '{ || }': [[['(', ')'], ['[', ']'], ['{', '}'], ['\\lfloor', '\\rfloor'],
          ['\\lceil', '\\rceil'], ['\\langle', '\\rangle'], ['/', '\\backslash'],
          ['|', '\\|']], [['\\uparrow', '\\Uparrow'], ['\\downarrow', '\\Downarrow'],
          ['\\updownarrow', '\\Updownarrow']], [['\\upharpoonleft',
          '\\downharpoonleft'], ['\\upharpoonright', '\\downharpoonright'],
          ['\\upuparrows', '\\downdownarrows']], [['\\nearrow', '\\nwarrow'],
          ['\\searrow', '\\swarrow']], [['\\quad', '\\,'], ['\\qquad',
          '\\:'], ['\\!', '\\;']], [['\\left', '\\right']]],
  '+ / -': [[['\\pm', '\\oplus'], ['\\mp', '\\ominus'], ['\\times', '\\otimes'],
          ['\\div', '\\odot'], ['\\star', '\\bigcirc'],
          ['\\circ', '\\setminus'], ['\\cdot', '\\bullet'], ['\\cap',
          '\\bigtriangleup'], ['\\cup', '\\bigtriangledown'], ['\\sqcap',
          '\\triangleleft'], ['\\sqcup', '\\triangleright'], ['\\vee',
          '\\dagger'], ['\\wedge', '\\ddagger']], [['\\leftarrow', '\\Leftarrow'],
          ['\\rightarrow', '\\Rightarrow'], ['\\leftrightarrow', '\\Leftrightarrow'],
          ['\\longleftarrow', '\\Longleftarrow'], ['\\longrightarrow',
          '\\Longrightarrow'], ['\\longleftrightarrow', '\\Longleftrightarrow'],
          ['\\longmapsto', '']]],
  '-->': [[['\\nleftarrow',
          '\\nLeftarrow'], ['\\nrightarrow', '\\nRightarrow'],
          ['\\nleftrightarrow', '\\nLeftrightarrow']], [['\\leftarrowtail',
          '\\rightarrowtail'], ['\\twoheadleftarrow', '\\twoheadrightarrow'],
          ['\\hookleftarrow', '\\hookrightarrow'], ['\\leftharpoonup',
          '\\rightharpoonup'], ['\\leftharpoondown', '\\rightharpoondown'],
          ['\\leftrightharpoons', '\\rightleftharpoons'], ['\\leftleftarrows',
          '\\rightrightarrows'], ['\\leftrightarrows', '\\rightleftarrows'],
          ['\\Lleftarrow', '\\Rrightarrow'], ['\\looparrowleft',
          '\\looparrowright'], ['\\curvearrowleft', '\\curvearrowright'],
          ['\\circlearrowleft', '\\circlearrowright'], ['\\Lsh', '\\Rsh']],
          [['\\dashleftarrow', '\\dashrightarrow'], ['\\leftrightsquigarrow',
          '\\rightsquigarrow'], ['\\mapsto', '\\multimap']]],

  // others are not used currently
  'Functions': [[['\\arccos', '\\arcsin', '\\arctan'], ['\\lim', '\\liminf',
                '\\limsup']], [['\\arg', '\\cos', '\\cosh', '\\cot', '\\\coth',
                '\\csc', '\\det', '\\dim', '\\exp', '\\gcd', '\\hom', '\\inf'],
                ['\\ker', '\\lg', '\\ln', '\\log', '\\max', '\\min', '\\sec',
                '\\sin', '\\sinh', '\\sup', '\\tan', '\\tanh']]],
  '< > =': [['<', '\\leq', '\\prec', '\\preceq', '\\ll', '\\subset',
            '\\subseteq', '\\sqsubseteq', '\\in', '\\vdash', '>', '\\geq',
            '\\succ', '\\succeq', '\\gg', '\\supset', '\\supseteq',
            '\\sqsupseteq', '\\ni', '\\dashv', ], ['\\equiv', '\\sim',
            '\\simeq', '\\asymp', '\\approx', '\\cong', '\\neq', '\\doteq',
            '\\models', '\\perp', '\\mid', '\\parallel', '\\smile', '\\frown',
            '\\propto', '\\bowtie', ], ['\\lhd', '\\rhd', '\\unlhd',
            '\\unrhd'], ],
  'AMS': [['\\hbar', '\\hslash', '\\backprime', '\\varnothing', '\\vartriangle',
          '\\triangledown', '\\angle', '\\sphericalangle', '\\measuredangle',
          '\\Finv', '\\exists', '\\nexists', '\\square', '\\blacksquare',
          '\\lozenge', '\\blacklozenge', '\\blacktriangle',
          '\\blacktriangledown', '\\bigstar', '\\complement', '\\mho', '\\eth',
          '\\diagup', '\\diagdown', ], ['\\Cap', '\\Cup', '\\circledS',
          '\\centerdot', '\\curlywedge', '\\curlyvee', '\\barwedge', '\\veebar',
          '\\boxdot', '\\circledast', '\\circleddash', '\\circledcirc', ],
          ['\\blacktriangleleft', '\\blacktriangleright', '\\therefore',
          '\\because'], ],
  'AMS < > =': [['\\leqq', '\\geqq', '\\leqslant', '\\geqslant',
                '\\eqslantless', '\\eqslantgtr', '\\lesssim', '\\gtrsim',
                '\\lessapprox', '\\gtrapprox', '\\lessdot', '\\gtrdot',
                '\\vartriangleleft', '\\vartriangleright', '\\trianglelefteq',
                '\\trianglerighteq', '\\precapprox', '\\succapprox',
                '\\precsim', '\\succsim', '\\preccurlyeq', '\\succcurlyeq',
                '\\curlyeqprec', '\\curlyeqsucc', '\\Subset', '\\Supset',
                '\\sqsubset', '\\sqsupset', '\\subseteq', '\\supseteq',
                '\\subseteqq', '\\supseteqq', ], ['\\lessgtr', '\\gtrless',
                '\\lesseqgtr', '\\gtreqless', '\\lesseqqgtr', '\\gtreqqless',
                '\\lll', '\\ggg', ], ['\\eqcirc', '\\circeq', '\\doteqdot',
                '\\risingdotseq', '\\fallingdotseq', '\\triangleq', '\\bumpeq',
                '\\Bumpeq', '\\vDash', '\\Vdash', '\\Vvdash', '\\between',
                '\\backsim', '\\thicksim', '\\backsimeq', '\\thickapprox',
                '\\approxeq', '\\varpropto', '\\smallsmile', '\\smallfrown',
                '\\shortmid', '\\shortparallel', '\\pitchfork',
                '\\backepsilon', ], ],
  'AMS NOT < > =': [['\\nless', '\\ngtr', '\\nleq', '\\ngeq', '\\nleqslant',
                    '\\ngeqslant', '\\nleqq', '\\ngeqq', '\\lneq', '\\gneq',
                    '\\lneqq', '\\gneqq', '\\lvertneqq', '\\gvertneqq',
                    '\\lnsim', '\\gnsim', '\\lnapprox', '\\gnapprox',
                    '\\ntriangleleft', '\\ntriangleright', '\\ntrianglelefteq',
                    '\\ntrianglerighteq', '\\nprec', '\\nsucc', '\\npreceq',
                    '\\nsucceq', '\\precneqq', '\\succneqq', '\\precnsim',
                    '\\succnsim', '\\precnapprox', '\\succnapprox',
                    '\\nsubseteq', '\\nsupseteq', '\\nsubseteqq',
                    '\\nsupseteqq', '\\subsetneq', '\\supsetneq',
                    '\\varsubsetneq', '\\varsupsetneq', '\\subsetneqq',
                    '\\supsetneqq', '\\varsubsetneqq', '\\varsupsetneqq', ],
                    ['\\nsim', '\\nshortmid', '\\nshortparallel', '\\nmid',
                    '\\nparallel', '\\ncong', '\\nvdash', '\\nvDash',
                    '\\nVdash', '\\nVDash'], ],

  // Exceptions are below
  'noRender': ['\\left', '\\right', '{', '}', '(', ')', '$'],
  'atypicalRender': {
    'x_k': ['_{', '}'],
    'x^k': ['^{', '}'],
    '\\mathbb{R}': ['\\mathbb{', '}'],
    '\\mathbf{B}': ['\\mathbf{', '}'],
    '\\mathcal{C}': ['\\mathcal{', '}'],
    '\\mathfrak{F}': ['\\mathfrak{', '}'],
    '\\mathrm{T}': ['\\mathrm{', '}'],
    '\\mathscr{A}': ['\\mathscr{', '}'],
    '\\mathsf{S}': ['\\mathsf{', '}'],
    '\\mathtt{N}': ['\\mathtt{', '}'],
    '\\hat{a}': ['\\hat{', '}'],
    '\\check{a}': ['\\check{', '}'],
    '\\breve{a}': ['\\breeve{', '}'],
    '\\acute{a}': ['\\acute{', '}'],
    '\\grave{a}': ['\\grave{', '}'],
    '\\tilde{a}': ['\\tilde{', '}'],
    '\\bar{a}': ['\\bar{', '}'],
    '\\vec{a}': ['\\vec{', '}'],
    '\\dot{a}': ['\\dot{', '}'],
    '\\ddot{a}': ['\\ddot{', '}'],
    '\\sqrt{abc}': ['\\sqrt{', '}'],
    '\\sqrt[n]{abc}': ['\\sqrt[n]{', '}'],
    '\\overline{abc}': ['\\overline{', '}'],
    '\\underline{abc}': ['\\underline{', '}'],
    '\\binom{m}{k}': ['\\binom{', '}{}'],
    '\\frac{num}{den}': ['\\frac{', '}{}'],
    // sorry that's such a dummy
    '\\mathbf{Bold}': ['\\textbf{', '}'],
    '\\mathfrak{Frac}': ['\\textfrak{', '}'],
    '\\mathit{Italic}': ['\\textit{', '}'],
    '\\mathrm{Roman}': ['\\textrm{', '}'],
    '\\mathsf{Sans}': ['\\textsf{', '}'],
    '\\mathtt{TT}': ['\\texttt{', '}'],
  },
  'atypicalNoRender': {
    '\\quad': '|__',
    '\\qquad': '|____',
    '\\!': '.|',
    '\\,': '|.',
    '\\:': '|..',
    '\\;': '|_',
  }
}
